trigger:
  branches:
    include:
      - main
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Example: If using Docker
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'  # or your service connection
    repository: 'yourdockeruser/yourapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

# Optional: Run unit tests or build your app here
# - script: npm install && npm test
